### PR TITLE
Added a loading bar at launch

### PR DESCRIPTION
**Pull request by LOVE2CODE123**
At launch a loading bar comes up

### CODE REVIEW

**Comment by LOVE2CODE123** [comment]
Please accept :cry:

**Comment by LOVE2CODE123** [comment]
:neckbeard:

**Comment by LOVE2CODE123** [comment]
:koala::koala::koala::koala::koala::koala:OHHHHH, CUTE KOALA SAYS MERGE MY PULL REQUEST:koala::koala::koala::koala::koala::koala:

**Comment by mharris3960** [comment]
Fine )(jYgjkghjkghjkghjkgjhgjghjkghjkghjghjghjgSorry there was a glitch dsjdklsjdkl;sjdlsjdl;jdkl;jskljskldjsla

**Comment by LOVE2CODE123** [comment]
Sweet, now you can sync it and run it

**Pull request merged**
